config/routes.rb
Rails.application.routes.draw do
  get 'books/index'
  get 'books/search'
  get 'books/show'
  get 'books/new'
  get 'books/edit'
  get 'books/create'
  get 'users/add_to_fav'
  get 'users/remove_from_fav'
  get 'users/add_writer'
  get 'users/remove_writer'
  resources :books
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :users, :only => [:index, :show, :add_to_fav, :remove_from_fav, :add_writer, :remove_writer]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable

  validates_presence_of :user_role
  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :password, if: :password_required?
  validates_confirmation_of :password, if: :password_required?

  has_many :written_books, :class_name => 'Book', :foreign_key => 'writer_id'
  has_and_belongs_to_many :books
  has_many :writers, class_name: "User", foreign_key: "publisher_id"
  belongs_to :publisher, class_name: "User", optional: true
  after_create :add_user_role


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.save
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"]) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

  private
    def add_user_role
      role = self.user_role
      return if role == "Lettore/Lettrice"
      if role == "Scrittore/Scrittrice"
        role = "writer"
      elsif role == "Casa Editrice"
        role = "publisher"
      else return
      end
      self.add_role(role)
      self.save
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
#  def index
#  end
def index
  @user = if params[:user]
    User.where('name LIKE ?', "%#{params[:user]}%") 
  else
    User.all
  end
end

  def task_params
    params.require(:task).permit(:name, :complete, :due_date, :term)
  end

  def show
    @user = User.find(params[:id])
  end
  def add_to_fav
    if !current_user.has_role? :publisher
      @book = Book.find(params[:book_param])
      if !current_user.books.include?(@book)
        current_user.books << @book
        current_user.save
      end
    end
  end
  def remove_from_fav
    if !current_user.has_role? :publisher
      @book = Book.find(params[:book_param])
      if current_user.books.include?(@book)
        current_user.books.delete(@book)
        current_user.save
      end
    end
  end
  def add_writer
    if current_user.has_role? :publisher
      @writer = User.find(params[:writer_to_add])
      if @writer
        if !current_user.writers.include?(@writer) && @writer.publisher == nil
          current_user.writers << @writer
          current_user.save
        else
          render 'already_there'
        end
      else
        render '_no_user_found'
      end
    end
  end
  def remove_writer
    if current_user.has_role? :publisher
      @writer = User.find(params[:writer_to_remove])
      if current_user.writers.include?(@writer) && @writer.publisher == current_user
        current_user.writers.delete(@writer)
        current_user.save
        @writer.publisher = nil
        @writer.save
      else
        render '_no_user_found'
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_no_user_found.html.erb
<div class="full_page">
  <h1 class="center_h1">UTENTE NON TROVATO</h1>
  <%= link_to 'Indietro', :back, id: "back_fav_info" %>
</div>

app/views/users/add_to_fav.html.erb
<div class="full_page">
  <h1 class="center_h1">LIBRO AGGIUNTO AI PREFERITI</h1>
  <% @prov_user = current_user %>
  <%= social_share_button_tag("#{@prov_user.name}", :allow_sites => %w(facebook), desc: "Ho appena aggiunto un libro ai preferiti su BookMark, vieni a vedere quali libri ho scelto!", :url => "https://bookmark-lassi.herokuapp.com/users/#{@prov_user.id}") %>
  <%= link_to 'Indietro', :back, id: "back_fav_info" %>
</div>

app/views/users/add_writer.html.erb
<div class="full_page">
  <h1 class="center_h1">SCRITTORE AGGIUNTO</h1>
  <%= link_to 'Indietro', :back, id: "back_fav_info" %>
</div>

app/views/users/already_there.html.erb
<div class="full_page">
  <h1 class="center_h1">HAI GIÀ AGGIUNTO QUESTO SCRITTORE</h1>
  <%= link_to 'Indietro', :back, id: "back_fav_info" %>
</div>

app/views/users/index.html.erb
<div class="full_page">
  <h1>Risultati della ricerca</h1>
  <% if Book.count > 0 %>
    <%= link_to 'Ricerca un libro', books_search_path, class: "btn btn-primary", id: "book_search"%>
  <% end %>
  <% if @user && @user.length > 0 %>
    <table>
      <thead>
        <tr>
          <th>Nome</th>
          <th>Email</th>
          <th>Ruolo</th>
          <th>Sede</th>
          <th>Bio</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @user.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.user_role %></td>
            <% if user.head_office && !user.head_office.empty? %>
              <td><%= user.head_office %></td>
            <% else %>
              <td>/</td>
            <% end %>
            <% if user.bio && !user.bio.empty? %>
              <td><%= truncate(user.bio, length: 50) %></td>
            <% else %>
              <td>/</td>
            <% end %>
            <td><%= link_to 'Mostra', user, id: "user_button" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <h2>Non è stato trovato nessun utente corrispondente ai criteri di ricerca</h2>
  <% end %>
</div>

app/views/users/remove_from_fav.html.erb
<div class="full_page">
  <h1 class="center_h1">LIBRO RIMOSSO DAI PREFERITI</h1>
  <%= link_to 'Indietro', :back, id: "back_fav_info" %>
</div>

app/views/users/remove_writer.html.erb
<div class="full_page">
  <h1 class="center_h1">SCRITTORE RIMOSSO</h1>
  <%= link_to 'Indietro', :back, id: "back_fav_info" %>
</div>

app/views/users/show.html.erb
<div class="full_page">
  <h1><%= @user.name.upcase %></h1>
  <% if @user.has_role?(:writer) %>
    <h2>SCRITTORE/SCRITTRICE</h2>
    <% if current_user.has_role?(:publisher) %>
      <% if current_user.writers && current_user.writers.include?(@user) %>
        <%= link_to 'Rimuovi dai tuoi scrittori', users_remove_writer_path(writer_to_remove: @user), class: "btn btn-primary" %>
      <% else %>
        <%= link_to 'Aggiungi ai tuoi scrittori', users_add_writer_path(writer_to_add: @user), class: "btn btn-primary" %>
      <% end %>
      <br />
      <br />
    <% end %>
    <div class="bio_section">
      <p class="profile_label">INFORMAZIONI PERSONALI</p>
      <% if !@user.bio || @user.bio.empty? %>
        <p style="font-size: 1.3em;">Non ha ancora inserito le sue informazioni!</p>
        <% if current_user == @user %>
          <%= link_to 'Modifica account', edit_user_registration_path, class: "btn btn-primary" %>
        <% end %>
      <% else %>
        <p style="font-size: 1.3em; padding-top: 20px;"><%= @user.bio %></p>
      <% end %>
    </div>
    <div class="written_books">
      <p class="profile_label">LIBRI DI CUI È AUTORE</p>
      <% if @user.written_books.length > 0 %>
        <table>
          <thead>
            <tr>
              <th>Titolo</th>
              <th>Genere</th>
              <th>Link Amazon</th>
              <th>Trama</th>
              <th>Anno di pubblicazione</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @user.written_books.each do |book| %>
              <tr>
                <td><%= book.title %></td>
                <td><%= book.genre %></td>
                <td><%= link_to "#{truncate(book.amazon, length: 20)}", book.amazon %></td>
                <td><%= truncate(book.plot, length: 300) %></td>
                <td><%= book.year %></td>
                <td><%= link_to 'Mostra', book, id: "book_button" %></td>
                <% if current_user == book.writer %>
                  <td><%= link_to 'Modifica', edit_book_path(book), id: "book_button" %></td>
                  <td><%= link_to 'Elimina', book, method: :delete, data: { confirm: 'Sei sicuro?' }, id: "book_button" %></td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p style="font-size: 1.3em;">Non ha ancora pubblicato libri!</p>
      <% end %>
      <% if @user == current_user %>
        <%= link_to 'Pubblica un libro', new_book_path, class: "btn btn-primary" %>
      <% end %>
    </div>
  <% elsif @user.has_role?(:publisher) %>
    <h2>CASA EDITRICE</h2>
    <div class="head_office_section">
      <p class="profile_label">SEDE</p>
      <% if !@user.head_office || @user.head_office.empty? %>
        <p style="font-size: 1.3em;">Non ha ancora inserito la sua sede!</p>
        <% if current_user == @user %>
          <%= link_to 'Modifica account', edit_user_registration_path, class: "btn btn-primary" %>
        <% end %>
      <% else %>
        <p style="font-size: 1.3em; padding-top: 20px;"><%= @user.head_office %></p>
      <% end %>
    </div>
    <div class="publisher_writers_section">
      <p class="profile_label">SCRITTORI PUBBLICATI</p>
      <% if !@user.writers || @user.writers.length == 0 %>
        <p style="font-size: 1.3em;">Non pubblica ancora nessuno scrittore!</p>
      <% else %>
        <table>
          <tbody>
            <% @user.writers.each do |writer| %>
              <tr>
                <td><%= link_to "#{writer.name}", user_url(id: writer.id) %></td>
                <% if current_user == @user %>
                  <td><%= link_to 'Rimuovi', users_remove_writer_path(writer_to_remove: writer) %></td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
      <% if current_user == @user %>
        <p style="font-size: 1.3em padding-top: 20px;">Per aggiungere gli scrittori, visita i loro profili</p>
      <% end %>
    </div>
  <% else %>
    <h2>LETTORE/LETTRICE</h2>
  <% end %>
  <% if !@user.has_role?(:publisher) %>
    <div class="preferred_books">
      <p class="profile_label">LIBRI PREFERITI</p>
      <% if @user.books.length > 0 %>
        <table>
          <thead>
            <tr>
              <th>Titolo</th>
              <th>Autore</th>
              <th>Genere</th>
              <th>Link Amazon</th>
              <th>Trama</th>
              <th>Anno di pubblicazione</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @user.books.each do |book| %>
              <tr>
                <td><%= book.title %></td>
                <% if book.writer %>
                  <td><%= link_to "#{book.writer.name}", user_url(id: book.writer.id) %></td>
                <% else %>
                  <td>/</td>
                <% end %>
                <td><%= book.genre %></td>
                <td><%= link_to "#{truncate(book.amazon, length: 20)}", book.amazon %></td>
                <td><%= truncate(book.plot, length: 300) %></td>
                <td><%= book.year %></td>
                <td><%= link_to 'Mostra', book, id: "book_button" %></td>
                <% if book.writer && current_user == book.writer %>
                  <td><%= link_to 'Modifica', edit_book_path(book), id: "book_button" %></td>
                  <td><%= link_to 'Elimina', book, method: :delete, data: { confirm: 'Sei sicuro?' }, id: "book_button" %></td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p style="font-size: 1.3em; bottom: 40px;">Non ha ancora scelto i suoi libri preferiti!</p>
      <% end %>
      <% if current_user == @user %>
        <p style="margin-bottom: 60px;"><%= link_to 'Vai a LIBRI', books_path, class: "btn btn-primary" %></p>
      <% end %>
    </div>
  <% end %>
</div>