config/routes.rb
Rails.application.routes.draw do
  get 'books/index'
  get 'books/search'
  get 'books/show'
  get 'books/new'
  get 'books/edit'
  get 'books/create'
  get 'users/add_to_fav'
  get 'users/remove_from_fav'
  get 'users/add_writer'
  get 'users/remove_writer'
  resources :books
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  resources :users, :only => [:index, :show, :add_to_fav, :remove_from_fav, :add_writer, :remove_writer]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, length: { minimum: 2, maximum: 50 }
  validates :genre, length: { minimum: 3, maximum: 30 }
  validates :plot, length: { minimum: 10, maximum: 8000 }
  validates :amazon, presence: true
  validate :validate_year
  belongs_to :writer, :class_name => 'User'
  has_and_belongs_to_many :users
  resourcify
  def validate_year
    current_year = Date.today.year
    if year && (year.to_i < 1000 || year.to_i > current_year)
      errors.add(:year, "deve essere valido")
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :require_writer, only: [:new, :create, :edit, :update, :destroy]
  include ApplicationHelper

  # GET /books
  # GET /books.json

# GET /books
  # GET /books.json
  #def index
   # @books = Book.all
  #end

#per la ricerca parte da qui
def index
  @books = if params[:book]
    Book.where('title LIKE ?', "%#{params[:book]}%") || Book.where('writer LIKE ?', "%#{params[:book]}%")
  else
    Book.all
  end
end

  def task_params
    params.require(:task).permit(:name, :complete, :due_date, :term)
  end
#finisce qui

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params.merge(writer_id: current_user.id))

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Libro caricato correttamente' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Libro aggiornato correttamente' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Libro eliminato correttamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :genre, :amazon, :plot, :year)
    end

    def require_writer
      unless has_role?(:writer)
        render 'shared/_writerneeded'
      end
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "errore") %> hanno impedito a questo libro di essere salvato:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, "Titolo" %>
    (minimo 2 caratteri, massimo 50)
    <br />
    <%= form.text_field :title, class: "text_field" %>
  </div>

  <div class="field">
    <%= form.label :genre, "Genere" %>
    (minimo 3 caratteri, massimo 30)
    <br />
    <%= form.text_field :genre, class: "text_field" %>
  </div>

  <div class="field">
    <%= form.label :amazon, "Link Amazon" %>
    <br />
    <%= form.text_field :amazon, class: "text_field" %>
  </div>

  <div class="field">
    <%= form.label :plot, "Trama" %>
    (minimo 10 caratteri, massimo 8000)
    <br />
    <%= form.text_area :plot, rows: "8" %>
  </div>

  <div class="field">
    <%= form.label :year, "Anno di pubblicazione" %>
    (dal 1000 a oggi)
    <br />
    <%= form.text_field :year %>
  </div>

  <div class="actions">
    <%= form.submit "Carica", id: "submit" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="overlay">
  <h1>Modifica libro</h1>

  <%= render 'form', book: @book %>

  <%= link_to 'Indietro', books_path, id: "link" %>
</div>

app/views/books/index.html.erb
<div class="full_page">
  <h1>Libri</h1>
  <% if has_role?(:writer) %>
    <%= link_to 'Aggiungi un libro', new_book_path, class: "btn btn-primary", id: "book_add"%>
  <% end %>
  <% if Book.count > 0 %>
    <%= link_to 'Ricerca un libro', books_search_path, class: "btn btn-primary", id: "book_search"%>
  <% end %>
  <% if @books.length > 0 %>
    <table>
      <thead>
        <tr>
          <th>Titolo</th>
          <th>Autore</th>
          <th>Genere</th>
          <th>Link Amazon</th>
          <th>Trama</th>
          <th>Anno di pubblicazione</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td><%= book.title %></td>
            <% if book.writer %>
              <td><%= link_to "#{book.writer.name}", user_url(id: book.writer.id) %></td>
            <% else %>
              <td>/</td>
            <% end %>
            <td><%= book.genre %></td>
            <td><%= link_to "#{truncate(book.amazon, length: 20)}", book.amazon %></td>
            <td><%= truncate(book.plot, length: 300) %></td>
            <td><%= book.year %></td>
            <td><%= link_to 'Mostra', book, id: "book_button" %></td>
            <% if book.writer && current_user == book.writer %>
              <td><%= link_to 'Modifica', edit_book_path(book), id: "book_button" %></td>
              <td><%= link_to 'Elimina', book, method: :delete, data: { confirm: 'Sei sicuro?' }, id: "book_button" %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <% if Book.count == 0 %>
      <h2>Non sono presenti libri al momento!</h2>
    <% else %>
      <h2>Nessun libro corrisponde ai criteri di ricerca</h2>
    <% end %>
  <% end %>
</div>

app/views/books/new.html.erb
<div class="overlay">
  <h1>Nuovo Libro</h1>

  <%= render 'form', book: @book %>

  <%= link_to 'Indietro', books_path, id: "link" %>
</div>

app/views/books/search.html.erb
<div class="full_page">
  <%= form_tag(books_path, method: :get, id: "research_books_form") do %>
    <%= text_field_tag :book, nil, placeholder: 'Titolo', id: "research_books_input", autofocus: true %>
    <%= submit_tag 'Cerca', class: "btn btn-primary" %>
  <% end %>
</div>

app/views/books/show.html.erb
<div class="full_page">

  <p style="margin-top: 25px;">
    <strong style="font-size: 3em;"><%= @book.title %></strong>
  </p>

  <% if @book.writer %>
    <% if @book.writer == current_user %>
      <p>
        <%= social_share_button_tag("#{@book.title}", :allow_sites => %w(facebook), desc: "Ho appena aggiunto un libro su BookMark: #{@book.title}") %>
      </p>
    <% end %>

    <p>
      <h2>Autore: <%= link_to "#{@book.writer.name}", user_url(id: @book.writer.id) %></h2>
    </p>
  <% end %>
    <h2>Genere: <%= @book.genre %></h2>
  </p>

  <p>
    <%= link_to 'Portami alla pagina su Amazon!', @book.amazon %>
  </p>

  <p>
    <h2>Anno di pubblicazione: <%= @book.year %></h2>
  </p>

  <p style="padding: 15px; text-align: center; font-size: 2em; line-height: 1.2; margin-left: 150px; margin-right: 150px; background: rgba(0, 0, 0, 0.2); border-radius: 20px;">
    <%= @book.plot %>
  </p>
  <% if !current_user.has_role?(:publisher) %>
    <% if current_user.books.include?(@book) %>
      <%= link_to 'Rimuovi dai preferiti', users_remove_from_fav_path(book_param: @book), id: 'add_or_remove_favs' %>
    <% else %>
      <%= link_to 'Aggiungi ai preferiti', users_add_to_fav_path(book_param: @book), id: 'add_or_remove_favs' %>
    <% end %>
  <% end %>
  <br />
  <br />
  <br />
  <% if @book.writer && @book.writer == current_user %>
    <%= link_to 'Modifica', edit_book_path(@book), id: "book_button_s" %> |
  <% end %>
  <%= link_to 'Vai a LIBRI', books_path, id: "book_button_s"%>
</div>